### PR TITLE
fix: useModal show handle no longer making every prop optional and add NiceModa.show component props generic

### PR DESCRIPTION
**Pull request by alexandredev3**
This PR addresses [this other PR](https://github.com/eBay/nice-modal-react/pull/28) where it was discussed how to make the types more flexible, but apparently the pr was discontinued.

So, based on @jakst example I created this PR.

examples:
missing_required_modal_props

required_props_prepared

I think the user should be able to pass a generic to say what props are expected.
modal_show

Here I think the user should pass the required props because, as far as I'm aware, when we add the `modal component` directly in `NiceModal.show()`, we don't have to register the modal or anything.
show_modal_component

### CODE REVIEW

**Comment by supnate** [comment]
Thanks @alexandredev3 , it looks like a nice solution. I will take a look later!

**Review by supnate — APPROVED** [review]

**Comment by supnate** [comment]
Hi @alexandredev3 , tried the PR locally, it behaves differently compared to the old `modal.show` api. For now, it seems always requires a type when create a modal: `create<MyCompProps>(MyModal)` instead of inferring type from `MyModal`. So I reverted the PR.

**Comment by alexandredev3** [comment]
Hello @supnate, can you provide a demo of what you've tried? I tried to replicate what you've described, but it behaves as said before in this PR. Maybe I'm missing something 🤔.

**Comment by supnate** [comment]
Hi @alexandredev3 , sorry that I missed the last message. My bad, it's not caused by your pr. now I've recovered it and published in the new version `v1.2.7`.

**Comment by duccadhv1** [comment]
how can i check required props when i use modal.show() with MyComponent name created by modal.create()?

**Pull request merged**
