### PR TITLE
feat: implement radix dialog helper

### PR DESCRIPTION
**Pull request by geisterfurz007**
This implements a helper for radix dialogs, closing #84.

I've also taken creative liberty to add some missing helpers to the default export.

### CODE REVIEW

**Comment by supnate** [comment]
Thanks @geisterfurz007 , LGTM. Would you like to also add the unit test for the radix helper?

**Comment by geisterfurz007** [comment]
@supnate yes, can do! Give me a couple days; my schedule is fairly busy :)

**Comment by supnate** [comment]
Thanks @geisterfurz007 ! No problem, take your time.

**Comment by joestrkr** [comment]
Thanks for the helper!

I am currently trying to figure out if there is a way to remove (instead of hide) the dialog but still keep the close animations. When I use the dialog by itself, it unmounts properly with animantion but when used together with NiceModal, I can only chose between hiding with animations or removing without animations.

**Comment by geisterfurz007** [comment]
@supnate I had some time to fiddle with the tests today; they failed (oops) and while setting up the radix helper in the example for a more isolated reproduction than in my production, I failed to install the dependencies on first attempt. The yarn.lock contains references to `npm.corp.ebay.com` which failed to resolve for me. Two questions:

1. Should I (next to the test) include an example implementation of the radix dialog in the example (probably yes)?
2. To do so, I have to get rid of the "broken" entries in the lockfile; is there a better strategy than delete and regenerate? I haven't tried find and replace yet, actually but maybe you have a better suggestion all around.

**Pull request closed without merging**
