### PR TITLE
chore: refine ts type

### PR DESCRIPTION
**Pull request by xxleyi**
Adjust some TS type definitions to provide better experience,  when using React components with useModal, show and register function.

### CODE REVIEW

**Comment by xxleyi** [comment]
Please hide whitespace when review the code. I don't know why I add many whitespace when copy&paste into Github online code editor.

**Comment by supnate** [comment]
LGTM. Thanks @xxleyi for this fantastic enhancement 💪 Great job!

**Comment by supnate** [comment]
Published the change to `v1.2.0`.

**Comment by lukasz-karolewski** [comment]
I'm having trouble understanding how it helps to specify type of the modal... From usage perspective what I'd expect that you strongly type modal props and return strongly typed promise 

but this changes does not accomplish that I still get Record<string, unknown> and Promise<unknown>
and I'm not sure how as a library user i benefit in any way from typing a modal... 

Maybe you can you examples of usage guys had in mind?

**Pull request merged**
